### ISSUE TITLE
typos in column names

### ISSUE THREAD

**Issue by cboulay** [s-ccs/pyedfread#13]
https://github.com/nwilming/pyedfread/blob/c2941e40a37d21d0fb87a6ecd1babce3dbaf0af0/pyedfread/edfread.pyx#L31-L32

`fhxyvel` --> `fhxvel`
`frxyvel` --> `frxvel`

What does the `f` prefix indicate, anyway? These fields are not in the API docs.

I think it would be helpful to have a comment [here](https://github.com/nwilming/pyedfread/blob/c2941e40a37d21d0fb87a6ecd1babce3dbaf0af0/pyedfread/data.pxd#L28-L33).

**Comment by nwilming** [comment]
The 'f' prefix comes from edf_data.h which is distributed with the EDF Access API. I guess there it indicates that these values are floats in the original data.

**Comment by cboulay** [comment]
I found it in the documentation after the fact. The `f` is for "fast". So, "fast gaze x velocity". Exactly how that is different from regular "gaze x velocity" isn't explained.

Anyway, you can close this if you already modified those two strings or let me know if you want me to make a pull request.
