### ISSUE TITLE
Github Discussions

### ISSUE THREAD

**Issue by alisamie97** [s-ccs/pyedfread#30]
Hello dear maintainers and developers
I am new to eye tracking and have been using the Eye Link 1000 plus recently in SRU Cognitive Lab for my first experiment.
I searched a lot for packages that can parse binocular data, and the only thing that I found is `https://github.com/s-ccs/pyedfread`
However, I could not install the package successfully until some minutes ago that @behinger applied some changes
Now I have it installed in my virtual env as this screenshot shows
![image](https://github.com/s-ccs/pyedfread/assets/23106000/2080e85d-7c56-4353-82d1-33bc6917f6c7)
Thanks to @behinger 
I suggest you add discussions to this repo so we can talk about it directly here, I guess there are some more people out there who need to use it.
I would like to help too.

**Comment by behinger** [comment]
Hi! Welcome and thanks for leaving a comment.

I recently took over maintenance from Niklas willing and Neil Morton.

Great idea of adding a discussion part. I will activate it soon :-)

I also plan to add a "how to contribute" part to the readne

**Comment by behinger** [comment]
Done!

![tenor-709744076](https://github.com/s-ccs/pyedfread/assets/10183650/bedf4253-8055-40d5-b28d-9fd7bccdf8f8)

**Comment by alisamie97** [comment]
Thanks, Im gonna add something
